
const app = new Vue({
    el:'#app',
    data:{
        name:'llx',
        username:'llx',
        password:'123456'
    },
    created(){
        this.loginByCookie();
    },
    methods:{
        login(){
            axios.post('/api/login',{name:this.username,password:this.password}).then(data=>{
                console.log(data);
            }).catch(err=>{
                console.log(err);
            })
        },
        register(){
            axios.post('/api/register',{name:this.username,password:this.password}).then(data=>{
                console.log(data);
            }).catch(err=>{
                console.log(err);
            })
        },
        loginByCookie(){
            axios.post('/api/cookieLogin').then(data=>{
                console.log(data);
            }).catch(err=>{
                console.log(err);
            })
        }
    }
});